name: Build and Deploy HTML Website

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-html-website:latest .

    - name: Save Docker image to file
      run: |
        docker save my-html-website:latest | gzip > my-html-website.tar.gz

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Docker image to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa my-html-website.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/

    - name: Deploy to AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}
          gunzip my-html-website.tar.gz
          docker load -i my-html-website.tar
          docker run -d -p 80:80 my-html-website:latest
        EOF
