name: Build and Deploy HTML Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in root directory
      run: ls -la

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: false
        tags: local/my-html-website:latest

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Deploy to EC2
      run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ec2-user@your-ec2-instance \
            'docker-compose pull && docker-compose up -d'
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        
    - name: Verify Deployment
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} 'docker ps'
