name: Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t your-image:latest .

      - name: Save Docker image as artifact
        run: docker save your-image:latest | gzip > your-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: your-image.tar.gz

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
                sudo amazon-linux-extras install docker -y
                sudo service docker start
                sudo usermod -aG docker $USER
            fi

            # Load Docker image and run container
            docker load -i /home/ubuntu/your-image.tar.gz
            docker run -d -p 80:80 your-image:latest
