name: Build and Deploy Docker Application

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false  # Build only, do not push
        tags: local/fasion-sample-web:latest

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Deploy Docker Compose
      run: |
        # Create a directory for Docker Compose files
        mkdir -p $HOME/docker-compose-app
        cp docker-compose.yml $HOME/docker-compose-app/
        cd $HOME/docker-compose-app

        # Build and start containers
        docker-compose build
        docker-compose up -d

    - name: Verify Deployment
      run: |
        # Check running containers
        docker ps
        # Optionally, perform other checks or tests
