name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: your-dockerhub-username/fasion-sample-web:latest

    - name: Set up Docker Compose
      uses: docker/compose-action@v2
      with:
        version: '2.17.0'

    - name: Deploy using Docker Compose
      run: |
        docker-compose pull
        docker-compose up -d
      env:
        DOCKER_HOST: tcp://your-server-ip:2376
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: /root/.docker
