name: Build and Deploy HTML Website

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # Use the root directory as context
        file: Dockerfile  # Dockerfile name
        push: false  # Build only, do not push
        tags: local/my-html-website:latest

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Prepare Docker Compose Directory
      run: |
        # Create directory for Docker Compose files
        mkdir -p $HOME/docker-compose-app

    - name: Copy Docker Compose file
      run: |
        # Copy the docker-compose.yml to the prepared directory
        cp docker-compose.yml $HOME/docker-compose-app/

    - name: Deploy Docker Compose
      run: |
        # Navigate to the Docker Compose directory
        cd $HOME/docker-compose-app
        # Build and start containers using Docker Compose
        docker-compose build || { echo 'Docker Compose build failed'; exit 1; }
        docker-compose up -d

    - name: Verify Deployment
      run: |
        # Check running containers
        docker ps
        # Optionally, perform other checks or tests
