name: Build and Deploy HTML Website

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # Set the context to the root directory
        file: Dockerfile  # Dockerfile location
        push: false  # Build only, do not push
        tags: local/my-html-website:latest

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Deploy Docker Compose
      run: |
        # Ensure docker-compose.yml is in the expected location
        mkdir -p $HOME/docker-compose-app
        cp docker-compose.yml $HOME/docker-compose-app/
        cd $HOME/docker-compose-app
        docker-compose build || { echo 'Docker Compose build failed'; exit 1; }
        docker-compose up -d

    - name: Verify Deployment
      run: |
        # Check running containers
        docker ps
        # Optionally, perform other checks or tests
